version: "3"
services:
    app:
        container_name: watchdog
        command: gunicorn --reload --bind 0.0.0.0:5001 app:app
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - ${APP_PORT}:5001
        depends_on:
          - postgre
          - redisearch
        environment:
          - DATABASE=postgres
          - SQL_HOST=postgre
          - SQL_PORT=5432
        env_file:
          - .env
        volumes:
          - $PWD:/usr/src/www
          - ./storage/logs:/usr/src/www/storage/logs
    postgre:
      container_name: watchdog_db
      image: postgres:11
      env_file:
        - .env
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_DB=${DB_DATABASE}
      ports:
        - ${DB_PORT}:5432
      restart: always
    redisearch:
      container_name: watchdog_search
      image: redislabs/redisearch
      volumes:
        - ./redis:/data
      env_file:
        - .env
      ports:
        - ${REDIS_PORT}:6379
      restart: always