version: "3"
services:
    app:
        container_name: watchTower
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${APP_PORT}:5000
        depends_on:
          - postgre
          - redisearch
        env_file:
          - .env
        volumes:
          - ${PWD}:/usr/src/www
          - ${PWD}/storage/logs:/tmp/logs
          - ${PWD}/storage/logs/watchtower:/tmp/logs/watchtower
    postgre:
      container_name: watchDb
      image: postgres:11
      env_file:
        - .env
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_DB=${DB_DATABASE}
      ports:
        - ${DB_PORT}:5432
      restart: always
    redisearch:
      container_name: watchSearch
      image: redislabs/redisearch
      volumes:
        - ${PWD}/redis:/data
      env_file:
        - .env
      ports:
        - ${REDIS_PORT}:6379
      restart: always
    adminer:
      container_name: watchAdmin
      image: adminer
      restart: always
      environment:
        - ADMINER_DESIGN=pepa-linha
        - ADMINER_DEFAULT_SERVER=postgre
      ports:
        - 8088:8080
