FROM python:3

EXPOSE 5000

WORKDIR /usr/src/www

COPY . /usr/src/www

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN cp .env.prod .env

RUN apt-get install -y libpq-dev && chmod u+x app.py

RUN export FLASK_APP=app.py && pip install --editable .

RUN pip install gunicorn

# CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5050"]

CMD ["entrypoint.prod.sh"]